name: FastAPI CI/CD with venv

on:
  push:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Clear Python cache (temporary fix)
      run: |
        rm -rf ~/.cache/pip
        rm -rf ~/.python-version

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: pytest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd ${{ secrets.APP_DIR }}
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          pkill uvicorn || true
          nohup venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000 > output.log 2>&1 &
